---
- name: Push Config from NetBox to Huawei
  hosts: all
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: huawei.vrp.vrp
  gather_facts: false
  tasks:
    - name: Push simple configuration
      huawei.vrp.vrp_config:
        lines:
         - sysname {{ inventory_hostname }}
         - vlan batch 15 16
