---
- name: Push Config from NetBox to Huawei
  hosts: all
  gather_facts: false
  tasks:
    - name: Push simple configuration
      ansible.netcommon.cli_config:
        config: |
          sysname {{ inventory_hostname }}
          vlan batch 15 16